name: svf-build

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: publish-svf-lib
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then sudo apt-get update       ; fi
          cat package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  - name: Trigger SVF-Python workflow
    run: |
      # check whether there is a change at SVF-linux-x86_64/Release-build
      cd ..
      CHANGED=$(git diff --name-only HEAD^ HEAD | grep '^SVF-linux-x86_64/Release-build/')
      
      if [ -z "$CHANGED" ]; then
        echo "No changes in SVF-linux-x86_64/Release-build, skipping trigger."
        exit 0
      else
        echo "Changes detected in SVF-linux-x86_64/Release-build. Proceeding to trigger downstream."
      
        git clone https://github.com/SVF-tools/SVF-Python.git
        cd SVF-Python
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit --allow-empty -m "trigger: changes in SVF-linux-x86_64/Release-build"
        git push https://yuleisui:${{secrets.yulei_git_key}}@github.com/SVF-tools/SVF-Python.git HEAD:main
      fi
