/**
 * SVF instance configuration header
 *
 * WARNING: This file is automatically generated; changes will be overwritten!
 *
 */

#ifndef SVF_CONFIG_H_IN
#define SVF_CONFIG_H_IN

// Expose base properties of this SVF instance
#define SVF_VERSION "3.1"
#define SVF_BUILD_TYPE "Release"
#define SVF_C_STANDARD "11"
#define SVF_CXX_STANDARD "17"
#define SVF_SHARED_LIBS 1
#define SVF_C_EXTENSIONS 0
#define SVF_CXX_EXTENSIONS 0
#define SVF_C_STANDARD_REQUIRED 0
#define SVF_CXX_STANDARD_REQUIRED 0

// Expose configurable build options for this SVF instance
#define SVF_NO_EH 0
#define SVF_NO_RTTI 0
#define SVF_USE_PIC 1
#define SVF_USE_LTO 0
#define SVF_USE_LLD 0
#define SVF_COVERAGE 0
#define SVF_DEBUG_INFO 0
#define SVF_WARN_AS_ERROR 1
#define SVF_EXPORT_DYNAMIC 0
#define SVF_ENABLE_ASSERTIONS 1
/* #undef SVF_SANITIZE */

// Expose the source/build locations of this SVF instance; only for legacy
// use-cases; should not be used directly by end users!
#define SVF_BUILD_EXTAPI_BC "/Users/runner/work/SVF/SVF/Release-build/lib/extapi.bc"
#define SVF_SOURCE_DIR "/Users/runner/work/SVF/SVF"
#define SVF_BUILD_DIR ""

// Define fallback for installed extapi.bc location to build tree's extapi.bc
#ifndef SVF_INSTALL_EXTAPI_BC
#    define SVF_INSTALL_EXTAPI_BC SVF_BUILD_EXTAPI_BC
#endif

#endif // SVF_CONFIG_H_IN
